In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

## Load the training data into feature matrix, class labels, and event ids:

In [2]:
from proj1_helpers import *
DATA_TRAIN_PATH = './train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

## Do your thing crazy machine learning thing here :) ...

In [3]:
np.shape(tX)
#np.shape(y)

(250000, 30)

In [4]:
#check for any NaN values
nans = np.isnan(tX)
np.unique(nans)

array([False])

## Feature reduction

### Removing features that are mostly one value

In [5]:
def f_too_many_values(tX,val=-999):
    #there is a lot of -999 values in the data
    #count the occurences for each feature
    f_to_remove = []
    for f in range(np.shape(tX)[1]):
        #print(tX[:,f])
        unique, counts = np.unique(tX[:,f], return_counts=True)
        count_dic = dict(zip(unique, counts))
        if val in count_dic:
            nb_999 = count_dic[val]
            nb_tot = np.shape(tX)[0]
            print(f"feature: ",f)
            per = (nb_999/nb_tot)*100
            print(f"number of ", val," values",nb_999,"which is",per,"%")
            if per > 10:
                f_to_remove.append(f)
    print(f"to remove",f_to_remove)
    return f_to_remove

In [6]:
#f_too_many_values(-999)

feature:  0
number of  -999  values 38114 which is 15.245600000000001 %
feature:  4
number of  -999  values 177457 which is 70.9828 %
feature:  5
number of  -999  values 177457 which is 70.9828 %
feature:  6
number of  -999  values 177457 which is 70.9828 %
feature:  12
number of  -999  values 177457 which is 70.9828 %
feature:  23
number of  -999  values 99913 which is 39.9652 %
feature:  24
number of  -999  values 99913 which is 39.9652 %
feature:  25
number of  -999  values 99913 which is 39.9652 %
feature:  26
number of  -999  values 177457 which is 70.9828 %
feature:  27
number of  -999  values 177457 which is 70.9828 %
feature:  28
number of  -999  values 177457 which is 70.9828 %
to remove [0, 4, 5, 6, 12, 23, 24, 25, 26, 27, 28]


[0, 4, 5, 6, 12, 23, 24, 25, 26, 27, 28]

In [7]:
#there is a lot of -999 values in the data
#count the occurences for each feature
f_to_remove = []
for f in range(np.shape(tX)[1]):
    #print(tX[:,f])
    unique, counts = np.unique(tX[:,f], return_counts=True)
    count_dic = dict(zip(unique, counts))
    if -999 in count_dic:
        nb_999 = count_dic[-999]
        nb_tot = np.shape(tX)[0]
        print(f"feature: ",f)
        per = (nb_999/nb_tot)*100
        print(f"number of -999 values",nb_999,"which is",per,"%")
        if per > 10:
            f_to_remove.append(f)
print(f"to remove",f_to_remove)

feature:  0
number of -999 values 38114 which is 15.245600000000001 %
feature:  4
number of -999 values 177457 which is 70.9828 %
feature:  5
number of -999 values 177457 which is 70.9828 %
feature:  6
number of -999 values 177457 which is 70.9828 %
feature:  12
number of -999 values 177457 which is 70.9828 %
feature:  23
number of -999 values 99913 which is 39.9652 %
feature:  24
number of -999 values 99913 which is 39.9652 %
feature:  25
number of -999 values 99913 which is 39.9652 %
feature:  26
number of -999 values 177457 which is 70.9828 %
feature:  27
number of -999 values 177457 which is 70.9828 %
feature:  28
number of -999 values 177457 which is 70.9828 %
to remove [0, 4, 5, 6, 12, 23, 24, 25, 26, 27, 28]


In [8]:
#delete the selected features
tX_red_f = np.delete(tX,f_to_remove,1)
np.shape(tX_red_f)

(250000, 19)

### Checking feature similarity

In [9]:
np.shape(tX_red_f)

(250000, 19)

In [18]:
def f_corr(corr_thr):
    #find correlation between the features
    #corr_thr = 8e-1
    corr = np.absolute(np.corrcoef(tX_red_f.T))
    bool_cor = np.greater(corr,corr_thr)
    f1,f2 = np.where(bool_cor)
    for i in range(len(f1)):
        if ~(f1[i] == f2[i]):
            corr_val = corr[f1[i],f2[i]]
            print(f"Features ",f1[i],"and",f2[i],"are strongly correlated. Value:",corr_val)

In [10]:
#find correlation between the features
corr_thr = 8e-1
corr = np.absolute(np.corrcoef(tX_red_f.T))
bool_cor = np.greater(corr,corr_thr)
f1,f2 = np.where(bool_cor)
#print(f1,f2)
for i in range(len(f1)):
    if ~(f1[i] == f2[i]):
        corr_val = corr[f1[i],f2[i]]
        print(f"Features ",f1[i],"and",f2[i],"are strongly correlated. Value:",corr_val)

Features  2 and 5 are strongly correlated. Value: 0.8327330666331234
Features  2 and 18 are strongly correlated. Value: 0.8086162641281681
Features  5 and 2 are strongly correlated. Value: 0.8327330666331234
Features  5 and 16 are strongly correlated. Value: 0.9044814595684981
Features  5 and 18 are strongly correlated. Value: 0.9656283889163993
Features  16 and 5 are strongly correlated. Value: 0.9044814595684981
Features  16 and 18 are strongly correlated. Value: 0.8844128574100243
Features  17 and 18 are strongly correlated. Value: 0.8043255943442028
Features  18 and 2 are strongly correlated. Value: 0.8086162641281681
Features  18 and 5 are strongly correlated. Value: 0.9656283889163995
Features  18 and 16 are strongly correlated. Value: 0.8844128574100243
Features  18 and 17 are strongly correlated. Value: 0.8043255943442027


Very strong corr between features 5,16,18 **The three features can be replaced by just feature 5**

additional corr between features 2 and 5,18 **2 can also be removed to just keep 5**

In [11]:
f_to_remove = np.array([2,16,18])

In [12]:
#delete the selected features
tX = np.delete(tX_red_f,f_to_remove,1)
np.shape(tX)

(250000, 16)

## Next step

In [13]:
y, tX, ids

(array([ 1., -1., -1., ...,  1., -1., -1.]),
 array([[ 51.655,  97.827,   3.064, ...,  16.824,  -0.277,   2.   ],
        [ 68.768, 103.235,   3.473, ...,  44.704,  -1.916,   1.   ],
        [162.172, 125.953,   3.148, ...,  54.283,  -2.186,   1.   ],
        ...,
        [ 60.526,  75.839,   2.39 , ...,  23.419,  -2.89 ,   1.   ],
        [ 19.362,  68.812,   3.365, ...,  12.15 ,   0.811,   0.   ],
        [ 72.756,  70.831,   2.025, ...,  40.729,  -1.596,   0.   ]]),
 array([100000, 100001, 100002, ..., 349997, 349998, 349999]))

In [14]:
# Group data


# Imputation Using Zero/Constant Values
tx = np.where(tX==-999, 0, tX) 

In [15]:
# Linear regression using gradient descent
from implementations import *

# Define the parameters of the algorithm.
max_iters = 50
gamma = 3 # use linspace to test various gamma values and look for the best ?

# Initialization
initial_w = np.zeros(tx.shape[1]+1)
tx_offset = np.empty([tx.shape[0], tx.shape[1]+1])
tx_offset[:, 0] = np.ones([tx.shape[0]]) 
tx_offset[:, 1:] = tx
loss_GD, w_GD = least_squares_GD(y, tx_offset, initial_w, max_iters, gamma)

print("Gradient Descent: loss={l}, w = {w}".format(
    l=loss_GD, w=w_GD))


Gradient Descent: loss=inf, w = [ 8.52653224e+253  4.15006558e+255  7.38025368e+255  1.89342813e+254
  2.01988205e+255  1.88476333e+256  1.28455718e+254  9.54519055e+252
  3.84753874e+255 -8.30154509e+251 -3.95830594e+251  4.54288660e+255
 -1.18637304e+252  3.52802235e+252  4.40636596e+255 -4.23968429e+251
  1.16216242e+254]


In [16]:
# Linear regression using stochastic gradient descent

# Define the parameters of the algorithm.
max_iters = 50
gamma = 3 # use linspace to test various gamma values and look for the best ?

# Initialization
# initial_w = np.zeros(tx.shape[1]+1)
# tx_offset = np.empty([tx.shape[0], tx.shape[1]+1])
# tx_offset[:, 0] = np.ones([tx.shape[0]]) 
# tx_offset[:, 1:] = tx
loss_GD, w_GD = least_squares_SGD(y, tx_offset, initial_w, max_iters, gamma)

print("Stochastic Gradient Descent: loss={l}, w = {w}".format(
    l=loss_GD, w=w_GD))

Stochastic Gradient Descent: loss=inf, w = [array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])]


## Generate predictions and save ouput in csv format for submission:

In [17]:
DATA_TEST_PATH = '' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

OSError:  not found.

In [ ]:
OUTPUT_PATH = '' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(weights, tX_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)